"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.requestItem = exports.WikibasePropertySnak = exports.WikibaseItemSnak = exports.UrlSnak = exports.TimeSnak = exports.TabularDataSnak = exports.StringSnak = exports.QuantitySnak = exports.MusicalNotationSnak = exports.MonolingualTextSnak = exports.MathSnak = exports.GlobeCoordinateSnak = exports.GeoShapeSnak = exports.ExternalIdentifierSnak = exports.CommonsMediaSnak = exports.Snak = exports.SiteLink = exports.Reference = exports.Label = exports.Item = exports.Description = exports.Statement = exports.Alias = void 0;
var Alias_1 = require("./Alias");
Object.defineProperty(exports, "Alias", { enumerable: true, get: function () { return __importDefault(Alias_1).default; } });
var Statement_1 = require("./Statement");
Object.defineProperty(exports, "Statement", { enumerable: true, get: function () { return __importDefault(Statement_1).default; } });
var Description_1 = require("./Description");
Object.defineProperty(exports, "Description", { enumerable: true, get: function () { return __importDefault(Description_1).default; } });
var Item_1 = require("./Item");
Object.defineProperty(exports, "Item", { enumerable: true, get: function () { return __importDefault(Item_1).default; } });
var Label_1 = require("./Label");
Object.defineProperty(exports, "Label", { enumerable: true, get: function () { return __importDefault(Label_1).default; } });
var Reference_1 = require("./Reference");
Object.defineProperty(exports, "Reference", { enumerable: true, get: function () { return __importDefault(Reference_1).default; } });
var SiteLink_1 = require("./SiteLink");
Object.defineProperty(exports, "SiteLink", { enumerable: true, get: function () { return __importDefault(SiteLink_1).default; } });
var Snak_1 = require("./Snak");
Object.defineProperty(exports, "Snak", { enumerable: true, get: function () { return __importDefault(Snak_1).default; } });
var CommonsMediaSnak_1 = require("./snaks/CommonsMediaSnak");
Object.defineProperty(exports, "CommonsMediaSnak", { enumerable: true, get: function () { return __importDefault(CommonsMediaSnak_1).default; } });
var ExternalIdentifierSnak_1 = require("./snaks/ExternalIdentifierSnak");
Object.defineProperty(exports, "ExternalIdentifierSnak", { enumerable: true, get: function () { return __importDefault(ExternalIdentifierSnak_1).default; } });
var GeoShapeSnak_1 = require("./snaks/GeoShapeSnak");
Object.defineProperty(exports, "GeoShapeSnak", { enumerable: true, get: function () { return __importDefault(GeoShapeSnak_1).default; } });
var GlobeCoordinateSnak_1 = require("./snaks/GlobeCoordinateSnak");
Object.defineProperty(exports, "GlobeCoordinateSnak", { enumerable: true, get: function () { return __importDefault(GlobeCoordinateSnak_1).default; } });
var MathSnak_1 = require("./snaks/MathSnak");
Object.defineProperty(exports, "MathSnak", { enumerable: true, get: function () { return __importDefault(MathSnak_1).default; } });
var MonolingualTextSnak_1 = require("./snaks/MonolingualTextSnak");
Object.defineProperty(exports, "MonolingualTextSnak", { enumerable: true, get: function () { return __importDefault(MonolingualTextSnak_1).default; } });
var MusicalNotationSnak_1 = require("./snaks/MusicalNotationSnak");
Object.defineProperty(exports, "MusicalNotationSnak", { enumerable: true, get: function () { return __importDefault(MusicalNotationSnak_1).default; } });
var QuantitySnak_1 = require("./snaks/QuantitySnak");
Object.defineProperty(exports, "QuantitySnak", { enumerable: true, get: function () { return __importDefault(QuantitySnak_1).default; } });
var StringSnak_1 = require("./snaks/StringSnak");
Object.defineProperty(exports, "StringSnak", { enumerable: true, get: function () { return __importDefault(StringSnak_1).default; } });
var TabularDataSnak_1 = require("./snaks/TabularDataSnak");
Object.defineProperty(exports, "TabularDataSnak", { enumerable: true, get: function () { return __importDefault(TabularDataSnak_1).default; } });
var TimeSnak_1 = require("./snaks/TimeSnak");
Object.defineProperty(exports, "TimeSnak", { enumerable: true, get: function () { return __importDefault(TimeSnak_1).default; } });
var UrlSnak_1 = require("./snaks/UrlSnak");
Object.defineProperty(exports, "UrlSnak", { enumerable: true, get: function () { return __importDefault(UrlSnak_1).default; } });
var WikibaseItemSnak_1 = require("./snaks/WikibaseItemSnak");
Object.defineProperty(exports, "WikibaseItemSnak", { enumerable: true, get: function () { return __importDefault(WikibaseItemSnak_1).default; } });
var WikibasePropertySnak_1 = require("./snaks/WikibasePropertySnak");
Object.defineProperty(exports, "WikibasePropertySnak", { enumerable: true, get: function () { return __importDefault(WikibasePropertySnak_1).default; } });
var request_1 = require("./tools/request");
Object.defineProperty(exports, "requestItem", { enumerable: true, get: function () { return __importDefault(request_1).default; } });
//# sourceMappingURL=index.js.map