name: "📚 Docs"
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: "📚 Build and deploy"
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6
        with:
          version: 10.33.0

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: 🔧 Install and Build
        run: |
          pnpm install --frozen-lockfile
          pnpm run docs

      - name: 🚀 Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          single-commit: true
